dist: xenial

before_script: sudo apt-get install pandoc
script: ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: web
  fqdn: algorithmica.org
  on:
    branch: master
